### ISSUE TITLE
Melhorar diagramas de caso de uso.

### ISSUE THREAD

**Issue by marquesr1** [felipeseolin/project-arqhub#2]
Criar diagramas de caso de uso para cada funcionalidade:
- [x] Gerenciamento de usuário
- [x] Gerenciamento de projetos arquitetônicos
- [x] Listagem e filtragem de projetos arquitetônicos

**Comment by Elian07** [comment]
Feito, já enviado ao drive.

**Comment by Elian07** [comment]
Feito, já enviado ao drive.
